# Generated by Django 6.0.7 on 2026-07-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('useremail', models.EmailField(max_length=254, unique=True)),
                ('usercontact', models.CharField(max_length=15)),
                ('userprofile', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('usergender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('userpassword', models.CharField(max_length=100)),
                ('userconfirmpassword', models.CharField(max_length=100)),
            ],
        ),
    ]
