# Generated by Django 6.0.7 on 2026-07-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('productdescription', models.TextField()),
                ('productprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productimage', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='userprofile',
            field=models.ImageField(upload_to='profile_pictures/'),
        ),
    ]
